import { SITE_DEFAULT_OG_IMAGE } from "@/lib/site";
import type { BlogPost } from "@/data/blog/types";

// Hand-written, country-agnostic educational guides. Unlike the rest of
// data/blog/blogPosts.ts, these are not generated by looping a template over
// every country - each entry below is authored individually, has its own
// distinct structure and argument, and carries an empty countrySlug so it is
// not tied to (or gated by) any single country's calculator coverage. See
// the flagship-allowlist note in blogPosts.ts and
// CONTENT_QUALITY_AUDIT_2026-07-06.md for why this distinction matters.

const GUIDE_AUTHOR = "William Petersen";
const GUIDE_DISCLAIMER =
  "This content is for general information only and is not tax, legal, financial, or accounting advice. Tax rules vary by country, region, and personal circumstances - confirm details with your employer's payroll team or your local tax authority.";
const GUIDE_CATEGORY = "salary-guides" as const;
const GUIDE_CATEGORY_LABEL = "Salary Guides";

export const GENERIC_GUIDE_POSTS: BlogPost[] = [
  // 1) Gross vs net salary
  {
    slug: "gross-vs-net-salary-explained",
    title: "Gross vs Net Salary: What Is the Difference?",
    metaTitle: "Gross vs Net Salary Explained: Definitions, Examples, FAQ",
    metaDescription:
      "Learn the difference between gross salary and net salary, what typically gets deducted along the way, and how to avoid the most common budgeting mistake when comparing job offers.",
    excerpt:
      "Gross salary is the number on your contract. Net salary is what actually lands in your bank account. Here is exactly what happens between the two.",
    category: GUIDE_CATEGORY,
    categoryLabel: GUIDE_CATEGORY_LABEL,
    countrySlug: "",
    countryName: "",
    articleType: "editorial-guide",
    keyword: "gross vs net salary",
    image: SITE_DEFAULT_OG_IMAGE,
    calculatorUrl: "/salary-calculator",
    updatedAt: "2026-07-06",
    author: GUIDE_AUTHOR,
    readingTime: "7 min read",
    heroEyebrow: "Salary basics",
    heroSummary:
      "Gross salary and net salary describe two different amounts, and confusing them is one of the fastest ways to misjudge a job offer or a monthly budget.",
    heroHighlights: [
      "Gross pay is the full amount agreed in your contract, before any deductions.",
      "Net pay is what you actually receive after tax, social contributions, and other withholdings.",
      "The gap between the two depends on your country, income level, and personal circumstances - not a fixed percentage.",
    ],
    researchStatus: "expanded",
    summaryBox: {
      title: "Key takeaways",
      items: [
        "Gross salary is the headline figure in a job advert or employment contract.",
        "Net salary (take-home pay) is gross salary minus income tax, social contributions, and any other mandatory or elected deductions.",
        "The same gross salary can produce very different net salaries in different countries, because tax brackets, allowances, and social contribution rates are not standardized internationally.",
        "Always budget using net salary, not gross salary - rent, groceries, and bills are paid with money that has already been taxed.",
      ],
    },
    whoThisGuideIsFor: [
      "Someone comparing a new job offer with their current pay and wants to know what actually changes in their bank account.",
      "A student or first-time employee who has never seen a payslip and is unsure why the number on the contract does not match the number that gets paid out.",
      "Anyone negotiating a salary who wants to know which number to focus on: the one the employer quotes, or the one that funds their monthly budget.",
    ],
    quickAnswers: [
      {
        question: "What is gross salary?",
        answer:
          "Gross salary is the full amount your employer agrees to pay you before any tax, social contributions, or other deductions are taken out. It is the number usually shown in a job advertisement or employment contract.",
      },
      {
        question: "What is net salary?",
        answer:
          "Net salary, also called take-home pay, is what actually reaches your bank account after income tax, social security or pension contributions, and any other mandatory or elected deductions have been subtracted from gross pay.",
      },
      {
        question: "Is net salary always lower than gross salary?",
        answer:
          "In almost every country, yes. There are rare edge cases involving refundable tax credits or benefits, but for the overwhelming majority of employees, net pay is lower than gross pay because some deduction almost always applies.",
      },
    ],
    quickFactsTable: {
      title: "Gross vs net salary at a glance",
      columns: ["Term", "What it means", "Where you see it"],
      rows: [
        ["Gross salary", "Full contractual pay before deductions", "Job adverts, employment contracts, offer letters"],
        ["Net salary", "Amount paid into your bank account", "Payslips, bank statements, take-home budgeting"],
        ["Typical deductions", "Income tax, social contributions, pension", "Payslip breakdown line items"],
        ["What to budget with", "Net salary, not gross salary", "Personal or household budget"],
      ],
    },
    sections: [
      {
        id: "the-core-difference",
        title: "The core difference between gross and net salary",
        paragraphs: [
          "Gross salary is the amount your employer agrees to pay you in exchange for your work, stated before anything is subtracted. If a job advertisement says the role pays a certain amount per year, that figure is almost always gross - it is the number used for comparing job offers, negotiating raises, and calculating pension contribution percentages.",
          "Net salary is what is left after your employer withholds the deductions it is legally required (or that you have chosen) to take out of your pay before it reaches your bank account. In most countries this includes income tax and some form of social insurance or pension contribution, and it can also include things like union dues, health insurance premiums, or salary-sacrifice arrangements such as a company pension scheme or a cycle-to-work benefit.",
          "The distance between gross and net salary is not a fixed percentage. It depends on how much you earn (many tax systems are progressive, so higher earners lose a larger share), which country and sometimes which region or city you work in, your personal circumstances (marital status, dependents, and any tax-free allowances you qualify for), and any voluntary deductions you have opted into.",
        ],
      },
      {
        id: "why-the-confusion-happens",
        title: "Why gross and net salary get confused",
        paragraphs: [
          "The confusion usually starts because job adverts, salary surveys, and casual conversations about pay almost always use gross figures, while the number that actually matters for day-to-day budgeting is net. Someone comparing two job offers by gross salary alone can walk into a pay cut in real terms if the new role is in a higher-tax bracket, a different country, or a role with a different pension contribution structure.",
          "A second source of confusion is that some benefits are described using gross-equivalent language even though they reduce your taxable income rather than your net pay directly - for example, pension contributions taken from gross pay before tax is calculated. Understanding whether a deduction happens before or after tax is calculated changes how much it actually costs you out of take-home pay.",
        ],
      },
      {
        id: "how-to-avoid-the-mistake",
        title: "How to avoid the most common budgeting mistake",
        paragraphs: [
          "The single most common mistake is building a monthly budget - rent, groceries, transport, savings - around a gross annual salary divided by twelve, instead of the actual net monthly amount that will land in your account. This overstates how much money is genuinely available and can lead to underestimating how tight a budget will be in the first few months of a new job or a pay rise.",
          "The safer approach is to convert any gross offer into an estimated net monthly figure before comparing it with fixed costs like rent or a mortgage. A salary calculator that models your country's income tax brackets, standard deductions, and social contribution rules can do this conversion far more accurately than a simple percentage guess, because tax systems rarely apply a single flat rate to the whole salary.",
        ],
      },
    ],
    practicalExample: {
      title: "A simple side-by-side example",
      scenario:
        "Two candidates are both offered the same round-number gross annual salary for similar roles, but in different countries with different income tax brackets, social contribution rates, and personal allowances.",
      steps: [
        "Start with the identical gross annual salary for both offers so the comparison is fair.",
        "Apply each country's income tax brackets and personal allowance to estimate income tax owed in each case.",
        "Apply each country's social security, pension, or equivalent contribution rate to the same gross salary.",
        "Subtract both amounts from the gross salary in each country to reach two different net salary figures.",
        "Compare the two resulting net monthly amounts against local living costs, not the identical gross figure both offers started with.",
      ],
      takeaway:
        "Two job offers with an identical gross salary can produce meaningfully different net salaries once local tax rules are applied - which is why gross salary alone is not a reliable way to compare offers across countries or even across regions within the same country.",
    },
    faqItems: [
      {
        question: "Does gross salary include bonuses?",
        answer:
          "It depends on how the bonus is structured and when it is paid, but recurring or contractual bonuses are usually added to gross taxable income for the period in which they are paid, which can temporarily push a person into paying a higher marginal rate on that portion of income.",
      },
      {
        question: "Is a pension contribution taken from gross or net pay?",
        answer:
          "Many pension schemes deduct contributions from gross pay before income tax is calculated, which reduces the amount of income tax owed compared with paying into the same pension from already-taxed net income. The exact treatment depends on the scheme and country, so check your payslip or ask payroll to confirm.",
      },
      {
        question: "Why did my net salary change even though my gross salary stayed the same?",
        answer:
          "Net salary can change without a change in gross salary if your tax code, personal allowance, contribution rates, benefit deductions, or household circumstances (such as marital status or number of dependents) change, or if the tax year itself changes and brackets or allowances are updated.",
      },
      {
        question: "Where can I estimate my own net salary?",
        answer:
          "Use the salary calculator on salaryincometax.com and select your country to see an estimate of net salary, total tax, and effective tax rate based on the gross amount you enter.",
      },
    ],
    verdictTitle: "Which number should you actually use?",
    verdictSummary:
      "Use gross salary for comparing job offers, negotiating pay, and calculating pension contribution percentages. Use net salary for every real-world budgeting decision - rent, savings targets, and monthly bills are all paid with money that has already been taxed.",
    sources: [
      "https://www.oecd.org/en/topics/taxation.html",
    ],
    relatedSlugs: [
      "how-income-tax-works",
      "monthly-vs-annual-salary",
      "how-to-use-a-salary-calculator",
      "income-tax-in-united-states",
    ],
  },

  // 2) How income tax works
  {
    slug: "how-income-tax-works",
    title: "How Income Tax Works: Brackets, Marginal Rates, and Take-Home Pay",
    metaTitle: "How Income Tax Works: Tax Brackets and Marginal Rate Explained",
    metaDescription:
      "A plain-English explanation of how progressive income tax brackets work, why moving into a higher bracket does not mean your whole salary is taxed at a higher rate, and how to estimate your own take-home pay.",
    excerpt:
      "Progressive income tax is one of the most misunderstood parts of a payslip. Here is how brackets, marginal rates, and effective rates actually work.",
    category: GUIDE_CATEGORY,
    categoryLabel: GUIDE_CATEGORY_LABEL,
    countrySlug: "",
    countryName: "",
    articleType: "editorial-guide",
    keyword: "how income tax works",
    image: SITE_DEFAULT_OG_IMAGE,
    calculatorUrl: "/salary-calculator",
    updatedAt: "2026-07-06",
    author: GUIDE_AUTHOR,
    readingTime: "8 min read",
    heroEyebrow: "Tax basics",
    heroSummary:
      "Most income tax systems are progressive, meaning higher portions of income are taxed at higher rates - but that does not mean your entire salary jumps to a higher rate the moment you cross a threshold.",
    heroHighlights: [
      "Progressive tax systems apply different rates to different slices of income, not your whole salary at once.",
      "Your marginal rate (the rate on your next dollar earned) is usually higher than your effective rate (the average rate across your whole income).",
      "Tax-free allowances and deductions reduce the amount of income that gets taxed in the first place.",
    ],
    researchStatus: "expanded",
    summaryBox: {
      title: "Key takeaways",
      items: [
        "A tax bracket defines a rate that applies only to the slice of income within that bracket, not to your entire salary.",
        "Your marginal tax rate is the rate applied to your next unit of income; your effective tax rate is your total tax divided by your total income, and it is almost always lower.",
        "Personal allowances and standard deductions reduce taxable income before brackets are applied, which lowers the tax bill regardless of which bracket you are in.",
        "\"Falling into a higher tax bracket\" from a raise or bonus almost never results in less take-home pay overall - only the portion of income inside the new bracket is taxed at the higher rate.",
      ],
    },
    whoThisGuideIsFor: [
      "Anyone who has heard the phrase \"I don't want a raise, it will push me into a higher tax bracket\" and wants to know if that is actually true.",
      "Someone trying to understand a payslip or a tax summary that lists several different rates.",
      "A person comparing take-home pay across two countries with different tax bracket structures.",
    ],
    quickAnswers: [
      {
        question: "What is a tax bracket?",
        answer:
          "A tax bracket is a range of income that is taxed at a specific rate. Progressive tax systems have several brackets, and as income rises, only the portion of income that falls within a higher bracket is taxed at that bracket's rate - not the entire income.",
      },
      {
        question: "What is the difference between marginal and effective tax rate?",
        answer:
          "Marginal tax rate is the rate applied to your next unit of income - essentially the rate on the top slice of your earnings. Effective tax rate is your total tax paid divided by your total income, which blends the lower rates applied to earlier brackets with the higher rate on the top slice, and is therefore almost always lower than the marginal rate.",
      },
      {
        question: "Does earning more always mean lower take-home pay after tax?",
        answer:
          "No. Because only the income within a new, higher bracket is taxed at the higher rate, earning more from a raise or bonus always increases your net pay in a standard progressive system, even if the increase is taxed at a higher marginal rate than your existing salary.",
      },
    ],
    quickFactsTable: {
      title: "Illustrative progressive brackets",
      columns: ["Income slice", "Illustrative rate", "What gets taxed at this rate"],
      rows: [
        ["First slice (e.g. up to a tax-free allowance)", "0%", "Income within the tax-free personal allowance"],
        ["Next slice", "Lower rate", "Only the income between the allowance and the next threshold"],
        ["Next slice", "Middle rate", "Only the income between that threshold and the next one"],
        ["Top slice", "Highest rate", "Only the income above the final threshold"],
      ],
    },
    sections: [
      {
        id: "what-a-bracket-really-means",
        title: "What a tax bracket really means",
        paragraphs: [
          "A tax bracket is a range of income with an assigned tax rate. In a progressive system, there are usually several brackets stacked on top of each other, each with its own rate, and the rate generally rises as income rises. The important detail that is often missed is that each rate only applies to the slice of income that falls within that specific bracket - not to the whole salary.",
          "For example, imagine a simplified three-bracket system: the first slice of income is tax-free, the next slice is taxed at a lower rate, and any income above that is taxed at a higher rate. Someone whose salary reaches into the top bracket does not pay the top rate on their entire salary - they pay 0% on the tax-free slice, the lower rate on the middle slice, and the higher rate only on the portion of income that exceeds the final threshold.",
        ],
      },
      {
        id: "marginal-vs-effective",
        title: "Marginal rate vs effective rate",
        paragraphs: [
          "Your marginal tax rate is the rate that applies to your next dollar, euro, or pound of income - it tells you how much of a raise, bonus, or extra freelance project you would actually keep after tax. Your effective tax rate is different: it is your total tax bill divided by your total income, blending together the 0% (or low) rate on earlier slices with the higher rate on the top slice.",
          "Because of how brackets stack, the effective rate is almost always meaningfully lower than the marginal rate, sometimes by a wide margin. This is the root of the common myth that a raise can leave you worse off - in a standard progressive system, that is mathematically very unlikely to happen, because only the new, higher-taxed slice is affected, and the rest of your income keeps being taxed exactly as before.",
        ],
      },
      {
        id: "allowances-and-deductions",
        title: "How allowances and deductions fit in",
        paragraphs: [
          "Most income tax systems also include a personal allowance or standard deduction: an amount of income that is not taxed at all, applied before the bracket structure kicks in. This is why the first bracket in many systems is effectively 0%. Additional deductions - for dependents, retirement contributions, or specific expenses - can reduce taxable income further, which lowers the tax bill regardless of which bracket someone's remaining income falls into.",
          "Some countries also use tax credits, which reduce the tax bill directly rather than reducing taxable income first. The distinction matters: a deduction is worth its value times your marginal rate, while a credit of the same face value is usually worth more, because it comes straight off the final tax bill. See the companion guide on tax deductions for a closer look at this difference.",
        ],
      },
    ],
    practicalExample: {
      title: "Working through a raise with a simplified bracket system",
      scenario:
        "An employee currently earns a salary that sits mostly in the middle tax bracket of a simplified three-bracket system, and is offered a raise that would push a portion of their income into the top bracket.",
      steps: [
        "Identify how much of the current salary falls into each existing bracket under the current rules.",
        "Add the raise amount and identify how much of the new total salary now falls into the top bracket.",
        "Apply the top bracket's rate only to the portion of income that newly falls above the top threshold.",
        "Add up tax owed across all brackets, including the unchanged lower brackets, to reach the new total tax bill.",
        "Compare new net pay with old net pay: it should be higher, because only the new top slice is taxed at the higher rate.",
      ],
      takeaway:
        "A raise that pushes part of your income into a higher bracket almost always increases your net pay overall - it just means the extra portion is taxed at a higher rate than your existing salary, not that your existing salary is retaxed.",
    },
    faqItems: [
      {
        question: "Can a raise ever actually reduce my take-home pay?",
        answer:
          "In a standard progressive income tax system, this is very unlikely, because only the new top slice of income is taxed at a higher rate. It becomes more plausible when a raise causes you to lose eligibility for an income-tested benefit, allowance, or subsidy that is withdrawn entirely (rather than gradually) once income crosses a threshold - that is a benefit-design issue, not how the tax brackets themselves work.",
      },
      {
        question: "Do all countries use the same number of tax brackets?",
        answer:
          "No. The number of brackets, the income thresholds, and the rates vary significantly by country and can change from one tax year to the next. Some countries use a flat tax rate instead of a progressive bracket system.",
      },
      {
        question: "How is my effective tax rate calculated?",
        answer:
          "Effective tax rate is calculated by dividing your total income tax paid by your total gross income for the period, then expressing that as a percentage. It reflects your average tax burden, not the rate on your next unit of income.",
      },
      {
        question: "Where can I see my own estimated brackets and effective rate?",
        answer:
          "Use the salary calculator on salaryincometax.com, select your country, and enter your gross salary to see an estimate of tax owed, effective tax rate, and net pay based on that country's current bracket structure.",
      },
    ],
    verdictTitle: "The one idea worth remembering",
    verdictSummary:
      "Progressive tax brackets tax slices of income, not your whole salary. A higher marginal rate on your next dollar earned is completely normal and does not mean your overall effective rate - or your take-home pay - moves against you.",
    sources: [
      "https://www.oecd.org/en/topics/taxation.html",
      "https://www.imf.org/en/Topics/taxation",
    ],
    relatedSlugs: [
      "tax-deductions-explained",
      "gross-vs-net-salary-explained",
      "how-to-use-a-salary-calculator",
      "income-tax-in-united-kingdom",
    ],
  },

  // 3) Tax deductions explained
  {
    slug: "tax-deductions-explained",
    title: "Tax Deductions Explained: Allowances, Deductions, and Credits",
    metaTitle: "Tax Deductions Explained: Allowances vs Deductions vs Credits",
    metaDescription:
      "Understand the difference between a tax-free personal allowance, a standard deduction, and a tax credit, and why the distinction changes how much a deduction is actually worth on your payslip.",
    excerpt:
      "Not all tax breaks work the same way. Here is the practical difference between allowances, deductions, and credits, and why it changes what they are worth to you.",
    category: GUIDE_CATEGORY,
    categoryLabel: GUIDE_CATEGORY_LABEL,
    countrySlug: "",
    countryName: "",
    articleType: "editorial-guide",
    keyword: "tax deductions explained",
    image: SITE_DEFAULT_OG_IMAGE,
    calculatorUrl: "/salary-calculator",
    updatedAt: "2026-07-06",
    author: GUIDE_AUTHOR,
    readingTime: "7 min read",
    heroEyebrow: "Tax basics",
    heroSummary:
      "Allowances, deductions, and tax credits all reduce what you owe, but they work through different mechanisms and are not worth the same amount for every taxpayer.",
    heroHighlights: [
      "A personal allowance or standard deduction reduces the income that gets taxed in the first place.",
      "A tax credit reduces the final tax bill directly, which usually makes it more valuable than a deduction of the same face value.",
      "Common deduction categories include retirement contributions, dependents, and certain work-related costs, but exact rules vary widely by country.",
    ],
    researchStatus: "expanded",
    summaryBox: {
      title: "Key takeaways",
      items: [
        "An allowance or deduction lowers your taxable income before tax rates are applied.",
        "A tax credit lowers your final tax bill directly, after tax has already been calculated.",
        "A deduction's value depends on your marginal tax rate; a credit's value generally does not.",
        "Retirement or pension contributions are a common example of a deduction taken from gross pay before income tax is calculated.",
      ],
    },
    whoThisGuideIsFor: [
      "Someone who keeps seeing the words \"allowance,\" \"deduction,\" and \"credit\" used interchangeably and wants to know if they actually mean the same thing.",
      "An employee deciding whether to increase pension contributions and wanting to understand the tax mechanics behind that choice.",
      "Anyone preparing for a conversation with payroll, HR, or a tax adviser and wanting to ask better questions.",
    ],
    quickAnswers: [
      {
        question: "What is a tax deduction?",
        answer:
          "A tax deduction reduces the amount of income that is subject to tax. It is applied before tax rates are calculated, so its value to you depends on your marginal tax rate - a deduction is worth more to someone in a higher tax bracket than to someone in a lower one.",
      },
      {
        question: "What is a tax credit?",
        answer:
          "A tax credit reduces your final tax bill directly, after tax has already been calculated on your income. Because it comes off the bill itself rather than the taxable income figure, a credit's value does not depend on your tax bracket in the same way a deduction's value does.",
      },
      {
        question: "Is a personal allowance the same as a deduction?",
        answer:
          "A personal allowance functions like an automatic standard deduction: an amount of income that is not taxed at all, applied to every eligible taxpayer without needing to itemize specific expenses.",
      },
    ],
    quickFactsTable: {
      title: "How each tax break works",
      columns: ["Type", "What it reduces", "When it applies"],
      rows: [
        ["Personal allowance", "Taxable income", "Automatically, up to a threshold amount"],
        ["Standard/itemized deduction", "Taxable income", "Before tax brackets are applied"],
        ["Tax credit", "Final tax bill", "After tax has been calculated"],
        ["Pension/retirement contribution", "Taxable income (in many systems)", "Before tax is calculated on that portion"],
      ],
    },
    sections: [
      {
        id: "allowance-vs-deduction",
        title: "Personal allowances and standard deductions",
        paragraphs: [
          "A personal allowance is an amount of income that is automatically exempt from tax, built into the structure of the tax system itself. It is one reason the first slice of income in many countries is effectively taxed at 0%, as covered in the companion guide on how income tax brackets work.",
          "A standard or itemized deduction works similarly in that it reduces taxable income before tax rates are applied, but it is often tied to a specific circumstance: a dependent, a work-related expense, a charitable donation, or a retirement contribution. Because deductions reduce taxable income rather than the final bill, their real-world value depends on your marginal tax rate - a deduction worth a fixed amount saves more tax for someone whose top slice of income is taxed at a higher rate than for someone in a lower bracket.",
        ],
      },
      {
        id: "tax-credits",
        title: "Why tax credits work differently",
        paragraphs: [
          "A tax credit is applied after your tax bill has already been calculated from your taxable income. Instead of reducing the income that gets taxed, it reduces the tax owed directly, unit for unit. This is why a credit of a given face value is often described as more valuable than a deduction of the same face value: its worth does not shrink for someone in a lower tax bracket the way a deduction's worth does.",
          "Some systems also distinguish between refundable and non-refundable credits. A refundable credit can reduce your tax bill below zero and result in a refund; a non-refundable credit can only reduce your tax bill down to zero. This distinction matters most for lower-income taxpayers whose tax bill may already be small.",
        ],
      },
      {
        id: "common-real-world-examples",
        title: "Common real-world examples",
        paragraphs: [
          "Retirement or pension contributions are one of the most common deductions: many systems allow contributions to be taken from gross pay before income tax is calculated, which is why increasing a pension contribution can reduce the income tax shown on a payslip, not just increase retirement savings.",
          "Dependent-related allowances (for a spouse or children), certain work-related expenses, and specific circumstances like disability or student status are other common categories, though exact eligibility and amounts vary widely by country and change from year to year. Because of this variation, treat any specific figure as a starting point to verify with your country's official tax authority or a qualified adviser, not a fixed rule that applies everywhere.",
        ],
      },
    ],
    practicalExample: {
      title: "Comparing a deduction with a credit of the same size",
      scenario:
        "Two taxpayers in different tax brackets each become eligible for a tax break with the same stated face value - one structured as a deduction, one structured as a credit - and want to know which is more valuable in practice.",
      steps: [
        "For the deduction, reduce each taxpayer's taxable income by the stated amount before applying their respective tax brackets.",
        "Calculate the tax saved by each taxpayer from the deduction: it equals the deduction amount multiplied by each person's marginal tax rate.",
        "For the credit, calculate each taxpayer's tax bill as normal, then subtract the same stated face value directly from the bill.",
        "Compare the tax saved by the deduction (which differs by bracket) with the tax saved by the credit (which is identical for both taxpayers).",
        "Conclude which type of tax break is more valuable for the taxpayer in the lower bracket, and which is unaffected by bracket at all.",
      ],
      takeaway:
        "A deduction's value scales with your tax bracket, so it is worth more to higher earners; a credit of the same face value delivers the same saving regardless of bracket, which is why it is generally considered the more powerful tool for reducing a tax bill.",
    },
    faqItems: [
      {
        question: "Do pension contributions reduce my taxable income or my final tax bill?",
        answer:
          "In many tax systems, pension or retirement contributions are deducted from gross pay before income tax is calculated, meaning they reduce taxable income rather than acting as a credit against the final bill. Confirm the exact treatment for your country and scheme, since rules vary.",
      },
      {
        question: "Are tax credits always better than deductions?",
        answer:
          "For most taxpayers, a credit of a given face value is worth at least as much as a deduction of the same face value, and often more for anyone whose marginal tax rate is below 100%. The exception is a very high earner in a system where the top marginal rate is close to the credit's implied rate, in which case the difference narrows.",
      },
      {
        question: "How do I know which deductions or credits I qualify for?",
        answer:
          "Eligibility rules are set by each country's tax authority and change over time. Check your national tax authority's official guidance, ask your employer's payroll department, or consult a qualified tax adviser rather than relying on a general estimate.",
      },
      {
        question: "Can a salary calculator show me the effect of a deduction?",
        answer:
          "Use the salary calculator on salaryincometax.com to see how standard deductions and allowances configured for your selected country affect your estimated take-home pay, alongside your income tax brackets and social contributions.",
      },
    ],
    verdictTitle: "The distinction that actually matters",
    verdictSummary:
      "Allowances and deductions reduce the income that gets taxed; credits reduce the tax bill itself. Understanding which one you are looking at explains why the same headline number can be worth different amounts to different taxpayers.",
    sources: [
      "https://www.oecd.org/en/topics/taxation.html",
    ],
    relatedSlugs: [
      "how-income-tax-works",
      "gross-vs-net-salary-explained",
      "how-to-use-a-salary-calculator",
      "income-tax-in-ireland",
    ],
  },

  // 4) Monthly vs annual salary
  {
    slug: "monthly-vs-annual-salary",
    title: "Monthly vs Annual Salary: How to Convert Pay Periods Correctly",
    metaTitle: "Monthly vs Annual Salary: How to Convert Pay Periods Correctly",
    metaDescription:
      "Learn how to convert between annual, monthly, weekly, daily, and hourly salary correctly, including the paid-months trap that catches out job offer comparisons.",
    excerpt:
      "Converting a salary between yearly, monthly, and hourly figures looks like simple division - until paid months, holiday pay, and rounding get involved.",
    category: GUIDE_CATEGORY,
    categoryLabel: GUIDE_CATEGORY_LABEL,
    countrySlug: "",
    countryName: "",
    articleType: "editorial-guide",
    keyword: "monthly vs annual salary",
    image: SITE_DEFAULT_OG_IMAGE,
    calculatorUrl: "/salary-calculator",
    updatedAt: "2026-07-06",
    author: GUIDE_AUTHOR,
    readingTime: "6 min read",
    heroEyebrow: "Pay periods",
    heroSummary:
      "Converting salary between yearly, monthly, weekly, and hourly figures looks like straightforward division, but paid months, holiday pay conventions, and rounding can all shift the result.",
    heroHighlights: [
      "Dividing annual salary by 12 assumes exactly 12 equal paycheques a year, which is not universal.",
      "Hourly-to-annual conversions depend heavily on assumed weekly hours and paid weeks per year.",
      "Small assumption differences compound quickly when comparing job offers quoted in different pay periods.",
    ],
    researchStatus: "expanded",
    summaryBox: {
      title: "Key takeaways",
      items: [
        "Annual salary divided by 12 gives an average monthly figure, but actual monthly pay can vary if bonuses, extra paid months, or irregular pay dates are involved.",
        "Hourly-to-annual conversions require an assumption about paid hours per week and paid weeks per year, and both assumptions materially change the result.",
        "When comparing two job offers quoted in different pay periods, convert both to the same period using the same underlying assumptions before comparing them.",
        "Always double check whether a quoted salary is gross or net before converting between periods - see the companion guide on gross vs net salary.",
      ],
    },
    whoThisGuideIsFor: [
      "Someone comparing a job offer quoted as an hourly rate with their current annual salary.",
      "A freelancer or contractor trying to translate a day rate into an equivalent annual salary for comparison purposes.",
      "Anyone budgeting monthly who wants to understand why a payslip amount does not always match annual salary divided by 12 exactly.",
    ],
    quickAnswers: [
      {
        question: "How do I convert annual salary to monthly salary?",
        answer:
          "The simplest method is to divide annual salary by 12, which gives an average monthly figure. This works well for salaries paid in 12 equal instalments a year, but check whether your employer or country uses a different number of paid months, since actual monthly pay can differ from this average.",
      },
      {
        question: "How do I convert an hourly rate to an annual salary?",
        answer:
          "Multiply the hourly rate by the number of hours worked per week, then multiply by the number of paid weeks per year. The result depends heavily on both assumptions, so use the actual contracted hours and paid weeks rather than a generic full-time estimate whenever possible.",
      },
      {
        question: "Why does my monthly pay not exactly equal my annual salary divided by 12?",
        answer:
          "This can happen if pay dates do not align neatly with calendar months, if a bonus or irregular payment is included in one month but not others, or if your country or employer pays salary in a different number of instalments than 12 across the year.",
      },
    ],
    quickFactsTable: {
      title: "Common conversion formulas",
      columns: ["From", "To", "Typical formula"],
      rows: [
        ["Annual salary", "Monthly salary", "Annual salary / 12 (or / actual paid months)"],
        ["Annual salary", "Weekly salary", "Annual salary / paid weeks per year"],
        ["Hourly rate", "Annual salary", "Hourly rate x hours per week x paid weeks per year"],
        ["Daily rate", "Annual salary", "Daily rate x paid days per week x paid weeks per year"],
      ],
    },
    sections: [
      {
        id: "the-simple-conversion-and-its-limits",
        title: "The simple conversion, and where it breaks down",
        paragraphs: [
          "The most common conversion - annual salary divided by 12 to get a monthly figure - works as an average, and is accurate for most salaried employees paid in 12 equal instalments across the year. The limit shows up when a country or employer uses a different payment structure, such as an extra payment in certain months, holiday-linked bonus payments, or 13th/14th-month payment conventions that exist in some countries. In those cases, the average monthly figure still describes annual income accurately, but the amount that lands in the bank account in any single month can be higher or lower than that average.",
          "A similar issue applies to weekly and daily conversions: annual salary divided by 52 assumes exactly 52 paid weeks, which does not account for unpaid leave, and daily-rate conversions depend on how many days per week are treated as paid working days.",
        ],
      },
      {
        id: "hourly-conversions",
        title: "Why hourly-to-annual conversions need more care",
        paragraphs: [
          "Converting an hourly rate into an annual salary requires two assumptions: how many hours are worked per week, and how many weeks are paid per year. A small change in either assumption meaningfully changes the annual figure - for example, comparing a role advertised at a certain hourly rate for a standard full-time week against a role with a shorter or longer standard working week can make two jobs with the same hourly rate look identical when the actual annual pay is quite different.",
          "This matters most for part-time work, contracting, and freelance comparisons, where hours per week vary by design. The safest approach is to use the actual contracted or expected hours for each specific role, rather than defaulting to a generic full-time assumption for every comparison.",
        ],
      },
      {
        id: "comparing-offers-fairly",
        title: "How to compare two offers quoted in different periods",
        paragraphs: [
          "When one job offer is quoted annually and another is quoted hourly or monthly, convert both to the same period using consistent assumptions before comparing them - and make sure both figures are on the same gross-or-net basis, since comparing a gross annual figure with a net monthly figure understates the true difference. See the companion guide on gross vs net salary for that distinction.",
          "It is also worth checking whether either offer includes irregular elements - a signing bonus, a relocation allowance, or a bonus tied to performance - since these can distort a simple period conversion if they are averaged into a headline annual figure but are not guaranteed every year.",
        ],
      },
    ],
    practicalExample: {
      title: "Comparing an hourly contract role with a salaried offer",
      scenario:
        "A candidate is comparing a contracting role paid at an hourly rate for a set number of hours per week against a salaried role quoted as an annual figure, and wants to compare them on the same basis.",
      steps: [
        "Multiply the contracting role's hourly rate by its stated weekly hours to get a weekly figure.",
        "Multiply that weekly figure by the number of weeks per year the contract is expected to run, accounting for any unpaid gaps between contracts.",
        "Compare the resulting annualized contracting income with the salaried role's annual figure on a gross basis.",
        "Convert both gross figures to an estimated net monthly amount using each role's applicable tax treatment.",
        "Compare the two net monthly figures, and separately note any benefits (pension contributions, paid leave, sick pay) that the salaried role includes but the contracting role does not.",
      ],
      takeaway:
        "An hourly contracting rate that looks higher than a salaried offer's equivalent hourly rate can still result in lower total annual income once unpaid gaps between contracts and missing benefits are accounted for - period conversion is only the first step of a fair comparison.",
    },
    faqItems: [
      {
        question: "Is annual salary divided by 12 always accurate for monthly pay?",
        answer:
          "It is accurate as an average for most employees paid in 12 equal monthly instalments. It becomes less precise if pay includes irregular bonuses, follows a 13th/14th-month convention used in some countries, or is affected by unpaid leave during the year.",
      },
      {
        question: "How many weeks per year should I use to convert an hourly or weekly rate?",
        answer:
          "This depends on how many weeks you are actually paid for. Full-time employment in many countries assumes something close to 52 paid weeks minus statutory unpaid leave, but contracting, seasonal work, and part-time arrangements can differ significantly - use the actual expected paid weeks for the specific role.",
      },
      {
        question: "Should I compare job offers using gross or net figures?",
        answer:
          "Compare using net figures whenever possible, since net pay is what actually funds your budget. If you only have gross figures for both offers, at minimum make sure both are being compared on the same gross basis and convert to net using each offer's applicable tax treatment before making a final decision.",
      },
      {
        question: "Can a salary calculator convert between pay periods for me?",
        answer:
          "Yes. The salary calculator on salaryincometax.com lets you enter pay as yearly, monthly, weekly, daily, or hourly, and returns the estimated result broken down across all of those periods after applying the selected country's tax rules.",
      },
    ],
    verdictTitle: "The habit that prevents costly mistakes",
    verdictSummary:
      "Always confirm which pay period a figure is quoted in, whether it is gross or net, and how many paid periods per year are assumed, before converting or comparing it with another offer. The conversion itself is simple; the assumptions behind it are where mistakes happen.",
    sources: [
      "https://www.ilo.org/topics/wages",
    ],
    relatedSlugs: [
      "gross-vs-net-salary-explained",
      "how-to-use-a-salary-calculator",
      "how-income-tax-works",
      "average-salary-in-canada-after-tax",
    ],
  },

  // 5) How to use a salary calculator
  {
    slug: "how-to-use-a-salary-calculator",
    title: "How to Use a Salary Calculator (Step by Step)",
    metaTitle: "How to Use a Salary Calculator: Step-by-Step Guide",
    metaDescription:
      "A step-by-step walkthrough of how to use an online salary calculator correctly: choosing a pay period, entering extra income, using reverse mode, and reading the results.",
    excerpt:
      "A salary calculator is only as accurate as the inputs you give it. Here is how to use one correctly, step by step, and how to read the results.",
    category: GUIDE_CATEGORY,
    categoryLabel: GUIDE_CATEGORY_LABEL,
    countrySlug: "",
    countryName: "",
    articleType: "editorial-guide",
    keyword: "how to use a salary calculator",
    image: SITE_DEFAULT_OG_IMAGE,
    calculatorUrl: "/salary-calculator",
    updatedAt: "2026-07-06",
    author: GUIDE_AUTHOR,
    readingTime: "6 min read",
    heroEyebrow: "Using this site",
    heroSummary:
      "A salary calculator can estimate take-home pay in seconds, but the result is only as reliable as the inputs behind it - here is how to use one correctly and interpret what it gives back.",
    heroHighlights: [
      "Choosing the correct pay period (yearly, monthly, weekly, daily, or hourly) is the first and most important input.",
      "Extra income, bonuses, and personal status all change the tax outcome and should be entered rather than ignored.",
      "Reverse mode lets you work backward from a target net salary to the gross salary you would need to negotiate.",
    ],
    researchStatus: "expanded",
    summaryBox: {
      title: "Key takeaways",
      items: [
        "Start by selecting your country, since income tax brackets, social contributions, and allowances are country-specific.",
        "Enter your salary in whichever period matches your offer or payslip - yearly, monthly, weekly, daily, or hourly - rather than converting it manually first.",
        "Add any extra income or bonus separately so it is included in the annual gross figure the calculator uses.",
        "Use reverse mode if you know the net salary you want and need to find the equivalent gross salary to negotiate.",
      ],
    },
    whoThisGuideIsFor: [
      "A first-time user of salaryincometax.com who wants a quick walkthrough before entering their own numbers.",
      "Someone comparing multiple job offers and wanting to make sure they are using every relevant input field correctly.",
      "Anyone who wants to understand what the results screen (gross salary, net salary, total tax, effective rate) actually means.",
    ],
    quickAnswers: [
      {
        question: "What is the first step in using a salary calculator?",
        answer:
          "Choose the correct country. Income tax brackets, social contributions, personal allowances, and any regional tax layers differ by country, so the calculator needs to know which country's rules to apply before anything else.",
      },
      {
        question: "Should I enter my salary as yearly or monthly?",
        answer:
          "Enter it in whichever period matches how it was quoted to you - yearly, monthly, weekly, daily, or hourly. The calculator annualizes the figure internally and returns results broken down across all periods, so there is no need to convert it manually first.",
      },
      {
        question: "What does reverse mode do?",
        answer:
          "Reverse mode lets you enter a target net (take-home) salary instead of a gross salary, and the calculator estimates the gross salary you would need to reach that net figure - useful when negotiating toward a specific take-home pay target.",
      },
    ],
    quickFactsTable: {
      title: "Input fields and what they affect",
      columns: ["Field", "What it does", "When to use it"],
      rows: [
        ["Country", "Selects which tax brackets and rules apply", "Always - select first"],
        ["Salary period", "Yearly, monthly, weekly, daily, or hourly", "Match to how your offer or payslip is quoted"],
        ["Extra income / bonus", "Adds to annual gross taxable income", "When a bonus or extra payment applies"],
        ["Personal status", "Adjusts allowances where the country model supports it", "When your marital or household status affects your tax rules"],
        ["Reverse calculation", "Switches the input to a target net salary", "When you know the take-home pay you want, not the gross offer"],
      ],
    },
    sections: [
      {
        id: "step-by-step-walkthrough",
        title: "Step-by-step walkthrough",
        paragraphs: [
          "Start on the salary calculator index page and choose the country whose tax rules should apply - this determines which income tax brackets, personal allowances, social contribution rates, and any regional tax layers are used in the estimate.",
          "Enter your salary in the period that matches how it was quoted to you: yearly, monthly, weekly, daily, or hourly. There is no need to convert it to an annual figure yourself first - the calculator annualizes the input internally using the country's default assumptions, which you can also see reflected in the results.",
          "If a bonus, allowance, or other extra income applies, add it using the extra income field rather than folding it into the main salary figure. This keeps the calculation transparent and lets the tool apply it correctly as part of annual taxable income.",
          "Select your personal status if the country model supports different statuses (such as single or married), since this can change the allowances or brackets applied. Then review the results: gross salary, net salary, total tax, and effective tax rate, along with a breakdown across yearly, monthly, weekly, daily, and hourly periods.",
        ],
      },
      {
        id: "using-reverse-mode",
        title: "Using reverse mode to work backward from a target",
        paragraphs: [
          "Reverse mode flips the calculation: instead of entering a gross salary and seeing the resulting net pay, you enter the net (take-home) salary you want, and the calculator estimates the gross salary that would be needed to reach it under the selected country's tax rules.",
          "This is particularly useful when negotiating a salary around a specific take-home pay target - for example, if you know you need a certain net monthly amount to cover fixed costs and want to know what gross salary to ask for, reverse mode gives you a starting estimate to bring into the conversation.",
        ],
      },
      {
        id: "reading-the-results",
        title: "How to read the results correctly",
        paragraphs: [
          "The results screen typically shows gross salary, net salary, total tax, and effective tax rate, alongside a period breakdown so you can see the equivalent yearly, monthly, weekly, daily, and hourly figures. Some pages also compare your result with a median salary or minimum wage benchmark for context, and your last several calculations may be saved locally in your browser so you can compare scenarios without re-entering data.",
          "Treat every result as a planning estimate, not a final payroll figure. Country tax models are built from published brackets, standard deductions, and social contribution rules, but real payslips can be affected by employer-specific benefits, local or regional rules not fully captured in the model, and personal circumstances that a general calculator cannot know in advance. When a decision is significant - accepting an offer, relocating, or planning a major purchase - confirm the estimate against a real payslip, payroll department, or qualified adviser.",
        ],
      },
    ],
    practicalExample: {
      title: "Using the calculator to evaluate a job offer with a signing bonus",
      scenario:
        "A candidate receives a job offer with a base annual salary plus a one-time signing bonus, and wants to estimate their first-year net pay including the bonus.",
      steps: [
        "Select the country where the role is based so the correct tax rules apply.",
        "Enter the base salary using the yearly period, matching how the offer was quoted.",
        "Add the signing bonus in the extra income field so it is included in first-year taxable income.",
        "Review the resulting net salary and effective tax rate, noting that the bonus year's effective rate may be higher than a typical year without it.",
        "Re-run the calculation without the bonus to see the ongoing net salary expected in subsequent years, for a more accurate long-term comparison.",
      ],
      takeaway:
        "Running the calculation twice - once with the signing bonus included and once without - gives a more accurate picture than a single estimate, since a one-time bonus can temporarily raise the effective tax rate in the year it is paid.",
    },
    faqItems: [
      {
        question: "Do I need to convert my salary to yearly before using the calculator?",
        answer:
          "No. Select the period that matches how your salary was quoted - yearly, monthly, weekly, daily, or hourly - and the calculator will annualize it internally and return results broken down across all periods.",
      },
      {
        question: "What should I do if my personal situation is not covered by the personal status options?",
        answer:
          "Use the closest available option as a starting estimate, and treat the result as directional rather than exact. For situations involving multiple income sources, complex benefits, or unusual household arrangements, confirm the final figure with a payroll department or qualified tax adviser.",
      },
      {
        question: "Is my calculation history saved anywhere other than my own browser?",
        answer:
          "Recent calculations are kept locally in your browser so you can compare scenarios without re-entering data. Check the site's privacy policy for full details on what is stored locally versus sent to any server.",
      },
      {
        question: "How accurate is the calculator compared with an actual payslip?",
        answer:
          "The calculator is built from published tax brackets, standard deductions, and social contribution rules for each supported country, but an actual payslip can differ due to employer-specific benefits, regional rules not fully captured in the model, or personal circumstances. Use the estimate for planning and comparison, and confirm important decisions against a real payslip or a qualified adviser.",
      },
    ],
    verdictTitle: "Get the most accurate estimate by being specific with your inputs",
    verdictSummary:
      "A salary calculator is most useful when every relevant input - country, pay period, extra income, and personal status - is filled in accurately. Skipping a field or guessing at a conversion manually is the most common way to get a misleading result.",
    sources: ["https://salaryincometax.com/sources"],
    relatedSlugs: [
      "gross-vs-net-salary-explained",
      "monthly-vs-annual-salary",
      "how-income-tax-works",
      "average-salary-in-australia-after-tax",
    ],
  },
];
